### ISSUE TITLE
Question about classifier bias 

### ISSUE THREAD

**Issue by csyanbin** [cambridge-mlg/cnaps#5]
In https://github.com/cambridge-mlg/cnaps/blob/master/src/adaptation_networks.py#L238, the bias_mean_processor is :
```
    (bias_means_processor): DenseResidualBlock(
      (linear1): Linear(in_features=512, out_features=1, bias=True)
      (linear2): Linear(in_features=1, out_features=1, bias=True)
      (linear3): Linear(in_features=1, out_features=1, bias=True)
      (elu): ELU(alpha=1.0)
    )
```
which is a little different from Table 13 of the paper. 

Is this a mistake or do I misunderstand something?

**Comment by jfb54** [comment]
Thanks for catching this. Indeed there is a discrepancy between the code and Table 13 in the paper. The code indicates that the output size after each linear layer is 1, while Table 13 indicates that the output of the first two layers is 512 and the final layer is 1. Given that the code generated the classification results in the paper, the code should be deemed correct.

**Comment by csyanbin** [comment]
Thanks for the instant feedback.

I ran the code for "film+ar" and got slightly worse (about -2%) results compared with the values reported in the paper. 
Are there any tips to reproduce the results or do you plan to release the checkpoint?

**Comment by jfb54** [comment]
Other than the code and instructions contained in this repository, there is no extra information that you need to reproduce the results. Due to the size of MetaDataset (i.e. a vary large number of possible tasks at both meta-train and meta-test time) and the randomness in the tasks generated by the MetaDataset task reader, the results do vary by a percent or two (up or down) from run to run. Even with a meta-trained model the test-time results will vary somewhat (usually within the error bars specified) due to differences in test tasks generated in subsequent runs. If it is useful, we can provide the meta-trained models that produced the results published in the paper.
